[package]
name = "minecraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
num-traits = "0.2.15"
indexmap = { version = "1.9.1" }
bytemuck = "1.12.1"
chumsky = "0.8.0"